name = "KnuckleTactic"
version = "0.1.0"
defaultTargets = ["KnuckleTactic"]

[[require]]
name = "LeanPy"
path = "../../.."

[[lean_lib]]
name = "KnuckleTactic"
moreLinkObjs = ["LeanPy/LeanPy:static", "LeanPy/leanPyNative:static"]
precompileModules = true
defaultFacets = ["shared"]
moreLinkArgs = [
  "-Wl,-headerpad_max_install_names",
]
