name = "PantographDemo"
version = "0.1.0"
defaultTargets = ["PantographDemo"]

[[require]]
name = "LeanPy"
path = "../../.."

[[lean_lib]]
name = "PantographDemo"
moreLinkObjs = ["LeanPy/LeanPy:static", "LeanPy/leanPyNative:static", "Pantograph/Pantograph:static", "Regex/Regex:static"]
precompileModules = true
defaultFacets = ["shared"]
moreLinkArgs = [
  "-Wl,-headerpad_max_install_names",
]
