name: Deploy documentation to Pages

on:
  push:
    branches: [main]

jobs:
  pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Set up Python
      run: uv python install 3.12

    - name: Install Python dependencies
      run: uv sync --extra docs

    - name: Build docs
      run: cd docs && uv run make html

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/build/html

    - id: deployment
      name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
